import type { Party } from "@/types";

export const MOCK_PARTIES: Party[] = [
  {
    id: "1",
    title: "ROV แรงค์ Diamond ขึ้น",
    game: "rov",
    game_name: "ROV",
    host_id: "u1",
    host_name: "SomchaiXX",
    max_members: 5,
    current_members: 3,
    status: "open",
    join_mode: "auto",
    tags: ["Diamond+", "ไม่ toxic"],
    discord_voice_link: "https://discord.gg/abc",
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "2",
    title: "Valorant Plat+ เท่านั้น",
    game: "valorant",
    game_name: "Valorant",
    host_id: "u2",
    host_name: "NongMin99",
    max_members: 5,
    current_members: 4,
    status: "open",
    join_mode: "approve",
    pending_count: 2,
    tags: ["Platinum+"],
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "3",
    title: "PUBG Squad สบายๆ",
    game: "pubg",
    game_name: "PUBG",
    host_id: "u3",
    host_name: "TomZaa",
    max_members: 4,
    current_members: 4,
    status: "full",
    join_mode: "auto",
    tags: ["สบายๆ"],
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "4",
    title: "Free Fire ฟาร์ม BP",
    game: "freefire",
    game_name: "Free Fire",
    host_id: "u4",
    host_name: "PimPim",
    max_members: 4,
    current_members: 1,
    status: "open",
    join_mode: "auto",
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "5",
    title: "ROV มา 5 แมน",
    game: "rov",
    game_name: "ROV",
    host_id: "u5",
    host_name: "BaanGamer",
    max_members: 5,
    current_members: 2,
    status: "open",
    join_mode: "approve",
    tags: ["Diamond+"],
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "6",
    title: "Valorant Ranked ซีเรียส",
    game: "valorant",
    game_name: "Valorant",
    host_id: "u6",
    host_name: "XRanker",
    max_members: 5,
    current_members: 3,
    status: "open",
    join_mode: "approve",
    discord_voice_link: "https://discord.gg/xyz",
    tags: ["ซีเรียส", "Plat+"],
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "7",
    title: "PUBG Solo to Squad",
    game: "pubg",
    game_name: "PUBG",
    host_id: "u7",
    host_name: "MaeMod",
    max_members: 4,
    current_members: 2,
    status: "open",
    join_mode: "auto",
    language: "both",
    created_at: "2024-01-01",
  },
  {
    id: "8",
    title: "ROV ฟาร์ม coin",
    game: "rov",
    game_name: "ROV",
    host_id: "u8",
    host_name: "KingROV",
    max_members: 5,
    current_members: 5,
    status: "full",
    join_mode: "auto",
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "9",
    title: "Free Fire คลิป content",
    game: "freefire",
    game_name: "Free Fire",
    host_id: "u9",
    host_name: "ContentZ",
    max_members: 4,
    current_members: 2,
    status: "open",
    join_mode: "approve",
    tags: ["content"],
    discord_voice_link: "https://discord.gg/cnt",
    language: "th",
    created_at: "2024-01-01",
  },
  {
    id: "10",
    title: "Valorant unrated สบายๆ",
    game: "valorant",
    game_name: "Valorant",
    host_id: "u10",
    host_name: "CasualV",
    max_members: 5,
    current_members: 1,
    status: "open",
    join_mode: "auto",
    tags: ["สบายๆ"],
    language: "en",
    created_at: "2024-01-01",
  },
];
